# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3abdd8137ccf39a53c576c5a6e8a89a136cf576cabc210fb3e212c566276c3337408aad84f93a976ddf991766bfdf30179670bef222f4e98cb38257d17586654

test:
  secret_key_base: b65a5a20aa35c3e58a2374520c8d310e3ebf29a6f75d0de1d9c8cab01d0b025a22e195ee2fd5e02bcfcbe024efeb54385f8a62ab3dfbb631709e565d40bc927e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
